# Generated by Django 4.2.1 on 2023-05-11 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_alter_pricerecord_adj_close"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pricerecord",
            unique_together={("company", "timestamp")},
        ),
    ]
